### ISSUE TITLE
Error when calling content.update()

### ISSUE THREAD

**Issue by ptreitler** [flamelink/flamelink-js-sdk#193]
I'm getting an error when using content.update() :
```
~\flamelink-import\node_modules\@flamelink\sdk-content-cf\dist\cjs\index.js:2358
                                    payload['_fl_meta_.createdFromLocale'] = firestoreService.FieldValue.delete();
                                                                                              ^
TypeError: Cannot read properties of undefined (reading 'FieldValue')
    at Object.<anonymous> (~\flamelink-import\node_modules\@flamelink\sdk-content-cf\dist\cjs\index.js:2358:95)
    at step (~\flamelink-import\node_modules\@flamelink\sdk-content-cf\dist\cjs\index.js:80:23)
    at Object.next (~\flamelink-import\node_modules\@flamelink\sdk-content-cf\dist\cjs\index.js:61:53)
    at fulfilled
```

I'm using the Firebase admin SDK and the Flamelink SDK (v1.0.0-rc.1) with the following modules:
```
import admin, { ServiceAccount } from "firebase-admin"
import flamelink from "flamelink/app"
import "flamelink/content"
import "flamelink/settings"
```

**Comment by ptreitler** [comment]
Workaround: Downgrading to `firebase-admin@9.12.0` seems to fix this problem.

**Comment by moschan** [comment]
It also works for me. Thanks!
